function [] = cop_plot(str_P, str_title)
%
% SYNOPSIS
%   [] = cop_plot(str_P, str_title)
%
% ARGS
%   str_P       in      directory containing cop data
%   str_title   in      title for plot
%
% DESC
%   The basic purpose of this function is to parse the cop.log
%   output generated by a run of the reinforcement learning
%   system (cop = Centre of Pressure of feet)
%
%   The cop.log file adheres to a strict format:
%   col #       meaning
%   [1-6]       miscellaneous logging pre-pends
%   7           time (iteration of system)
%   8           episode
%   9           episode length
%   10          cop data from left foot
%   11          cop data from right foot
%
% HISTORY
%   30 October 2002
%   o Initial design and coding (based on Ahmet's script)
%

close all

n = 2;                         % Total number of plots

disp('Reading cop data...');
homeDir=pwd;
cd(str_P)
!cat cop.log | awk '{print $9" "$10" "$11'} > plot_cop.log
load('plot_cop.log');
cd(homeDir);

records = size(plot_cop);
length  = records(1,1)-1;
t       = plot_cop(1:length,1);

str_number  = sprintf('\t\t\t[%d samples read]', length);
disp(str_number);

foot = {'LEFT', 'RIGHT'};
h = figure(1);
set(h, 'Position', [200 200 800 800])

disp('Preparing plots...');

set(gca, 'XTickLabel', []);

subplot(2,1,1);
plot(t, plot_cop(1:length, 2));
ylabel('LEFT');

subplot(2,1,2);
plot(t, plot_cop(1:length, 3));
ylabel('RIGHT');

xlabel('time (50 ms steps)');



