function [] = emg_plot(str_P, str_title)
%
% SYNOPSIS
%   [] = emg_plot(str_P, str_title)
%
% ARGS
%   str_P       in      directory containing emg data
%   str_title   in      title for plot
%
% DESC
%   The basic purpose of this function is to parse the emg.log
%   output generated by a run of the reinforcement learning
%   system.
%
%   The emg.log file adheres to a strict format:
%   col #       meaning
%   [1-6]       miscellaneous logging pre-pends
%   7           time (iteration of system)
%   8           episode
%   9           episode length
%   [10-17]     emg data from left leg
%   [18-25]     emg data from right leg
%   10 | 18         tibialis anterior (l/r)
%   11 | 19         soleus (l/r)
%   12 | 20         gastrocnemius (l/r)
%   13 | 21         vasti (l/r)
%   14 | 22         femoris (l/r)
%   15 | 23         hamstrings (l/r)
%   16 | 24         glutei  (l/r)
%   17 | 25         iliopsoas (l/r)
%
%   Note that the data plotted are the *activation* levels
%   sent from each muscle's agent to the muscle itself.
%
% HISTORY
%   30 October 2002
%   o Initial design and coding (based on Ahmet's script)
%

close all

n = 16;                         % Total number of plots

disp('Reading emg data...');
homeDir=pwd;
cd(str_P)
!cat emg.log | awk '{print $9" "$10" "$11" "$12" "$13" "$14" "$15" "$16" "$17" "$18" "$19" "$20" "$21" "$22" "$23" "$24" "$25'} > plot_emg.log
load('plot_emg.log');
cd(homeDir);

records     = size(plot_emg);
length      = records(1,1)-1;
t           = plot_emg(1:length,1);

str_number  = sprintf('\t\t\t[%d samples read]', length);
disp(str_number);

muscles = {'TIB', 'SOL', 'GAS', 'VAS', 'FEM', 'HAM', 'GLU', 'ILI'};
h = figure(1);
set(h, 'Position', [200 200 800 800])

disp('Preparing plots...');
for i = 1:8
    % Left leg
    subplot(n/2,2,(i-1)*2+1)
    plot(t, plot_emg(1:length,i+1))
    %stairs(t, plot_emg(1:length,i+1))
    ylabel(muscles{i})
    if i < 8
        set(gca, 'XTickLabel', [])
    end
    if i==8
        xlabel('(Left leg) time (50 ms intervals)');
    end

    % Right leg
    subplot(n/2,2,(i)*2)
    plot(t, plot_emg(1:length,i+9))
    %stairs(t, plot_emg(1:length,i+9))
    if i < 8
        set(gca, 'XTickLabel', [])
    end
    if i==8
        xlabel('(Right leg) time (50 ms intervals)');
    end
end

%title(str_title);

